# Optimizing Functions of Two Varibales
f(w1, w2) = 0.1*w1^2 + 2*w2^2



# Exercise1: Gradient Descent
W = W - α ∗ dW

## Import thư viện

In [4]:
import numpy as np

## Tính đạo hàm

In [5]:
def df_w(W):
    """
    Thực hiện tính gradient của dw1 và dw2
    Arguments:
    W -- np.array [w1, w2]
    Returns:
    dW -- np.array [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    """
    #################### YOUR CODE HERE ####################

    w1, w2 = W

    dw1 = 0.2*w1
    dw2 = 4*w2

    dW = np.array([dw1, dw2])

    ########################################################
    return dW

## Cập nhật tham số

In [6]:
def sgd(W, dW, lr):
    """
    Thực hiện thuật tóa Gradient Descent để update w1 và w2
    Arguments:
    W -- np.array: [w1, w2]
    dW -- np.array: [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    lr -- float: learning rate
    Returns:
    W -- np.array: [w1, w2] w1 và w2 sau khi đã update
    """
    #################### YOUR CODE HERE ####################

    W = W - lr*dW

    ########################################################
    return W

## Dựa vào thuật toán Gradient Descent các bạn thực hiện tìm điểm minimum của function (1) với các tham số sau khởi tạo:
w1 = −5,
w2 = −2,

α = 0.4

In [9]:
def train_p1(optimizer, lr, epochs):
    """
    Thực hiện tìm điểm minimum của function (1) dựa vào thuật toán
    được truyền vào từ optimizer
    Arguments:
    optimize : function thực hiện thuật toán optimization cụ thể
    lr -- float: learning rate
    epoch -- int: số lượng lần (epoch) lặp để tìm điểm minimum
    Returns:
    results -- list: list các cặp điểm [w1, w2] sau mỗi epoch (mỗi lần cập nhật)
    """

    # initial point
    W = np.array([-5, -2], dtype=np.float32)

    # list of results
    results = [W]
    #################### YOUR CODE HERE ####################
    # Tạo vòng lặp theo số lần epochs
    # tìm gradient dW gồm dw1 và dw2
    # dùng thuật toán optimization cập nhật w1 và w2
    # append cặp [w1, w2] vào list results

    for i in range(epochs):
        dW = df_w(W)
        W = optimizer(W, dW, lr)
        results.append(W)

    ########################################################
    return results

## Train epoch = 2

In [10]:
alpha = 0.4
train_p1(sgd, lr=alpha, epochs=2)

[array([-5., -2.], dtype=float32),
 array([-4.6,  1.2]),
 array([-4.232, -0.72 ])]

## Train epoch = 30

In [11]:
alpha = 0.4
train_p1(sgd, lr=alpha, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.6,  1.2]),
 array([-4.232, -0.72 ]),
 array([-3.89344,  0.432  ]),
 array([-3.5819648, -0.2592   ]),
 array([-3.29540762,  0.15552   ]),
 array([-3.03177501, -0.093312  ]),
 array([-2.78923301,  0.0559872 ]),
 array([-2.56609437, -0.03359232]),
 array([-2.36080682,  0.02015539]),
 array([-2.17194227, -0.01209324]),
 array([-1.99818689,  0.00725594]),
 array([-1.83833194, -0.00435356]),
 array([-1.69126538,  0.00261214]),
 array([-1.55596415, -0.00156728]),
 array([-1.43148702e+00,  9.40369969e-04]),
 array([-1.31696806e+00, -5.64221981e-04]),
 array([-1.21161061e+00,  3.38533189e-04]),
 array([-1.11468176e+00, -2.03119913e-04]),
 array([-1.02550722e+00,  1.21871948e-04]),
 array([-9.43466646e-01, -7.31231688e-05]),
 array([-8.67989314e-01,  4.38739013e-05]),
 array([-7.98550169e-01, -2.63243408e-05]),
 array([-7.34666155e-01,  1.57946045e-05]),
 array([-6.75892863e-01, -9.47676268e-06]),
 array([-6.21821434e-01,  5.68605761e-06]),
 array([-

# Exercise2: Gradient Descent + Momentum
Vt = βVt−1 + (1 − β)dWt

Wt = Wt − α ∗ Vt


## Import thư viện

In [12]:
import numpy as np

## Tính Đạo Hàm

In [13]:
def df_w(W):
    """
    Thực hiện tính gradient của dw1 và dw2
    Arguments:
    W -- np.array [w1, w2]
    Returns:
    dW -- np.array [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    """
    #################### YOUR CODE HERE ####################

    w1, w2 = W

    dw1 = 0.2*w1
    dw2 = 4*w2

    dW = np.array([dw1, dw2])

    ########################################################
    return dW

## Cập Nhật Tham Số

In [14]:
def sgd_momentum(W, dW, lr, V, beta):
    """
    Thực hiện thuật tóan Gradient Descent + Momentum để update w1 và w2
    Arguments:
    W -- np.array: [w1, w2]
    dW -- np.array: [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    lr -- float: learning rate
    V -- np.array: [v1, v2] Exponentially weighted averages gradients
    beta -- float: hệ số long-range average
    Returns:
    W -- np.array: [w1, w2] w1 và w2 sau khi đã update
    V -- np.array: [v1, v2] Exponentially weighted averages gradients sau khi đã cập nhật
    """
    #################### YOUR CODE HERE ####################

    V = beta*V + (1-beta)*dW
    W = W - lr*V

    ########################################################
    return W, V

## Dựa vào thuật toán Gradient Descent và momentum các bạn thực hiện tìm điểm minimum của function (1) với các tham số sau khởi tạo:
w1 = −5, w2 = −2,

v1 = 0, v2 = 0,

α = 0.6, β = 0.5

In [15]:
def train_p2(optimizer, lr, epochs):
    """
    Thực hiện tìm điểm minimum của function (1) dựa vào thuật toán
    được truyền vào từ optimizer
    Arguments:
    optimize : function thực hiện thuật toán optimization cụ thể
    lr -- float: learning rate
    epochs -- int: số lượng lần (epoch) lặp để tìm điểm minimum
    Returns:
    results -- list: list các cặp điểm [w1, w2] sau mỗi epoch (mỗi lần cập nhật)
    """
    # initial
    W = np.array([-5, -2], dtype=np.float32)
    V = np.array([0, 0], dtype=np.float32)
    results = [W]
    #################### YOUR CODE HERE ####################
    # Tạo vòng lặp theo số lần epochs
    # tìm gradient dW gồm dw1 và dw2
    # dùng thuật toán optimization cập nhật w1, w2, v1, v2
    # append cặp [w1, w2] vào list results

    beta = 0.5
    for i in range(epochs):
        dW = df_w(W)
        W, V = optimizer(W, dW, lr, V, beta)
        results.append(W)

    ########################################################
    return results

## Train epoch = 2

In [16]:
alpha = 0.6
train_p2(sgd_momentum, lr=alpha, epochs=2)

[array([-5., -2.], dtype=float32),
 array([-4.7,  0.4]),
 array([-4.268,  1.12 ])]

## Train epoch = 30

In [17]:
alpha = 0.6
train_p2(sgd_momentum, lr=alpha, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.7,  0.4]),
 array([-4.268,  1.12 ]),
 array([-3.79592,  0.136  ]),
 array([-3.3321248, -0.5192   ]),
 array([-2.90029971, -0.22376   ]),
 array([-2.51036919,  0.192472  ]),
 array([-2.16478177,  0.1696216 ]),
 array([-1.86210116, -0.04534952]),
 array([-1.59903478, -0.09841566]),
 array([-1.37155951, -0.00684994]),
 array([-1.1755283 ,  0.04715285]),
 array([-1.006981  ,  0.01757082]),
 array([-0.86228849, -0.01830518]),
 array([-0.73820492, -0.01427696]),
 array([-0.63187084,  0.0048695 ]),
 array([-0.54079155,  0.00859933]),
 array([-4.62804416e-01,  1.45050014e-04]),
 array([-0.39604258, -0.00425615]),
 array([-0.33889911, -0.00134937]),
 array([-0.28999343,  0.00172326]),
 array([-0.24814098,  0.00119166]),
 array([-0.2123263 , -0.00050413]),
 array([-0.18167938, -0.00074707]),
 array([-1.55455157e-01,  2.79448010e-05]),
 array([-0.13301574,  0.00038192]),
 array([-1.13815082e-01,  1.00603444e-04]),
 array([-0.09738585, -0.00016078]),
 

# Exercise3: RMSProp

St = γ*St−1 + (1 − γ)*dWt^2

Wt = Wt − α ∗dW/ √(St + ϵ)

## Import thư viện

In [18]:
import numpy as np

## Tính Đạo Hàm

In [19]:
def df_w(W):
    """
    Thực hiện tính gradient của dw1 và dw2
    Arguments:
    W -- np.array [w1, w2]
    Returns:
    dW -- np.array [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    """
    #################### YOUR CODE HERE ####################

    w1, w2 = W

    dw1 = 0.2*w1
    dw2 = 4*w2

    dW = np.array([dw1, dw2])

    ########################################################
    return dW

## Dựa vào thuật toán RMSProp các bạn thực hiện tìm điểm minimum của function (1) với các tham số sau khởi tạo:
w1 = −5,
w2 = −2,

s1 = 0,
s2 = 0,

α = 0.3,
γ = 0.9,
ϵ = 10−6

## Cập Nhật Tham Số

In [20]:
def RMSProp(W, dW, lr, S, gamma):
    """
    Thực hiện thuật tóan RMSProp để update w1 và w2
    Arguments:
    W -- np.array: [w1, w2]
    dW -- np.array: [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    lr -- float: learning rate
    S -- np.array: [s1, s2] Exponentially weighted averages bình phương gradients
    gamma -- float: hệ số long-range average
    Returns:
    W -- np.array: [w1, w2] w1 và w2 sau khi đã update
    S -- np.array: [s1, s2] Exponentially weighted averages bình phương gradients sau khi đã cập nhật
    """
    epsilon = 1e-6
    #################### YOUR CODE HERE ####################

    S = gamma*S + (1-gamma)*dW**2
    adapt_lr = lr/np.sqrt(S + epsilon)
    W = W - adapt_lr*dW

    ########################################################
    return W, S

In [21]:
def train_p3(optimizer, lr, epochs):
    """
    Thực hiện tìm điểm minimum của function (1) dựa vào thuật toán
    được truyền vào từ optimizer
    Arguments:
    optimize : function thực hiện thuật toán optimization cụ thể
    lr -- float: learning rate
    epochs -- int: số lượng lần (epoch) lặp để tìm điểm minimum
    Returns:
    results -- list: list các cặp điểm [w1, w2] sau mỗi epoch (mỗi lần cập nhật)
    """
    # initial
    W = np.array([-5, -2], dtype=np.float32)
    S = np.array([0, 0], dtype=np.float32)
    results = [W]
    #################### YOUR CODE HERE ####################
    # Tạo vòng lặp theo số lần epochs
    # tìm gradient dW gồm dw1 và dw2
    # dùng thuật toán optimization cập nhật w1, w2, s1, s2
    # append cặp [w1, w2] vào list results

    gamma = 0.9
    for i in range(epochs):
        dW = df_w(W)
        W, S = optimizer(W, dW, lr, S, gamma)
        results.append(W)

    ########################################################
    return results

## Train epoch = 2

In [22]:
alpha = 0.3
train_p3(RMSProp, lr=alpha, epochs=2)

[array([-5., -2.], dtype=float32),
 array([-4.05132145, -1.05131678]),
 array([-3.43519754, -0.59152343])]

## Train epoch = 30

In [23]:
alpha = 0.3
train_p3(RMSProp, lr=alpha, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.05132145, -1.05131678]),
 array([-3.43519754, -0.59152343]),
 array([-2.95893693, -0.3294394 ]),
 array([-2.56546289, -0.17756482]),
 array([-2.22920552, -0.09163256]),
 array([-1.93626752, -0.04494499]),
 array([-1.67817686, -0.02081423]),
 array([-1.44934985, -0.00903559]),
 array([-1.24588199, -0.00364591]),
 array([-1.06490301, -0.00135351]),
 array([-9.04202260e-01, -4.56444431e-04]),
 array([-7.61996495e-01, -1.37562928e-04]),
 array([-6.36778499e-01, -3.62601019e-05]),
 array([-5.27215237e-01, -8.11337456e-06]),
 array([-4.32078505e-01, -1.47473412e-06]),
 array([-3.50198507e-01, -2.02783991e-07]),
 array([-2.80434649e-01, -1.84231187e-08]),
 array([-2.21659834e-01, -7.67742748e-10]),
 array([-1.72755512e-01,  7.80451998e-12]),
 array([-1.32615134e-01, -5.05794800e-13]),
 array([-1.00153779e-01,  6.19123501e-14]),
 array([-7.43217708e-02, -1.13373781e-14]),
 array([-5.41201278e-02,  2.80166702e-15]),
 array([-3.86159157e-02, -8.81341

# Exercise4: Adam
Vt = β1*Vt−1 + (1 − β1)*dWt

St = β2*St−1 + (1 − β2)*dWt2

Vcorr = Vt/(1 − β1^t)

Scorr = St/(1 − β2^t)

Wt = Wt − α ∗Vcorr/ √(Scorr+ ϵ)


## Import thư viện

In [24]:
import numpy as np

## Tính Đạo Hàm

In [26]:
def df_w(W):
    """
    Thực hiện tính gradient của dw1 và dw2
    Arguments:
    W -- np.array [w1, w2]
    Returns:
    dW -- np.array [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    """
    #################### YOUR CODE HERE ####################

    w1, w2 = W

    dw1 = 0.2*w1
    dw2 = 4*w2

    dW = np.array([dw1, dw2])

    ########################################################
    return dW

## Dựa vào thuật toán Adam các bạn thực hiện tìm điểm minimum của function (1) với các tham số sau khởi tạo:
w1 = −5,
w2 = −2,

v1 = 0,
v2 = 0,

s1 = 0,
s2 = 0,


β1 = 0.9,
β2 = 0.999,

α = 0.2,
ϵ = 10−6

## Cập Nhật Tham Số

In [27]:
def Adam(W, dW, lr, V, S, beta1, beta2, t):
    """
    Thực hiện thuật tóan Adam để update w1 và w2
    Arguments:
    W -- np.array: [w1, w2]
    dW -- np.array: [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    lr -- float: learning rate
    V -- np.array: [v1, v2] Exponentially weighted averages gradients
    S -- np.array: [s1, s2] Exponentially weighted averages bình phương gradients
    beta1 -- float: hệ số long-range average cho V
    beta2 -- float: hệ số long-range average cho S
    t -- int: lần thứ t update (bắt đầu bằng 1)
    Returns:
    W -- np.array: [w1, w2] w1 và w2 sau khi đã update
    V -- np.array: [v1, v2] Exponentially weighted averages gradients sau khi đã cập nhật
    S -- np.array: [s1, s2] Exponentially weighted averages bình phương gradients sau khi đã cập nhật
    """
    epsilon = 1e-6
    #################### YOUR CODE HERE ####################

    V = beta1*V + (1-beta1)*dW
    S = beta2*S + (1-beta2)*dW**2

    Vcorr = V/(1-beta1**t)
    Scorr = S/(1-beta2**t)

    adapt_lr = lr/np.sqrt(Scorr + epsilon)
    W = W - adapt_lr*Vcorr

    ########################################################
    return W, V, S

In [29]:
def train_p4(optimizer, lr, epochs):
    """
    Thực hiện tìm điểm minimum của function (1) dựa vào thuật toán Adam
    được truyền vào từ optimizer
    Arguments:
    optimize : function thực hiện thuật toán optimization cụ thể
    lr -- float: learning rate
    epochs -- int: số lượng lần (epoch) lặp để tìm điểm minimum
    Returns:
    results -- list: list các cặp điểm [w1, w2] sau mỗi epoch (mỗi lần cập nhật)
    """
    # initial
    W = np.array([-5, -2], dtype=np.float32)
    V = np.array([0, 0], dtype=np.float32)
    S = np.array([0, 0], dtype=np.float32)
    results = [W]
    #################### YOUR CODE HERE ####################
    # Tạo vòng lặp theo số lần epochs
    # tìm gradient dW gồm dw1 và dw2
    # dùng thuật toán optimization cập nhật w1, w2, s1, s2, v1, v2
    # append cặp [w1, w2] vào list results
    # các bạn lưu ý mỗi lần lặp nhớ lấy t (lần thứ t lặp) và t bất đầu bằng 1

    beta1 = 0.9
    beta2 = 0.999
    t = 1
    for i in range(epochs):
        dW = df_w(W)
        W, V, S = optimizer(W, dW, lr, V, S, beta1, beta2, t)
        results.append(W)
        t += 1

    ########################################################
    return results

## Train epoch = 2

In [30]:
alpha = 0.2
train_p4(Adam, lr=alpha, epochs=2)

[array([-5., -2.], dtype=float32),
 array([-4.8000001, -1.8      ]),
 array([-4.60025458, -1.60082446])]

## Train epoch = 30

In [31]:
alpha = 0.2
train_p4(Adam, lr=alpha, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.8000001, -1.8      ]),
 array([-4.60025458, -1.60082446]),
 array([-4.40094818, -1.40317255]),
 array([-4.20227724, -1.20787812]),
 array([-4.00444983, -1.01592732]),
 array([-3.80768579, -0.82847292]),
 array([-3.61221664, -0.64684142]),
 array([-3.41828545, -0.47252746]),
 array([-3.22614653, -0.30716913]),
 array([-3.03606497, -0.15249832]),
 array([-2.84831603, -0.01026302]),
 array([-2.66318433,  0.11787577]),
 array([-2.48096283,  0.23046186]),
 array([-2.30195156,  0.32635894]),
 array([-2.12645613,  0.40484216]),
 array([-1.95478597,  0.46564981]),
 array([-1.7872523 ,  0.50898816]),
 array([-1.62416583,  0.53549455]),
 array([-1.46583419,  0.54617153]),
 array([-1.31255919,  0.54230818]),
 array([-1.16463376,  0.52540208]),
 array([-1.02233886,  0.49709058]),
 array([-0.88594013,  0.45909505]),
 array([-0.75568468,  0.41317772]),
 array([-0.63179773,  0.36110878]),
 array([-0.51447945,  0.30464032]),
 array([-0.40390206,  0.2454839